name: Release Binaries

on:
  push:
    tags:
      - "*"

jobs:
  auto-release:
    runs-on: ubuntu-latest

    steps:
      - name: Build Devcontainers
        run: |
          echo ${{ toJSON(github) }}

